image: gitlab.d5.lan:5005/sazhen/sazhen:latest
stages:
  - build
job1:
  stage: build
  script:
    - cd /builds/Sazhen/Sazhen/
    - ls
    - cd ./firmware
    - ls
    - mkdir /builds/Sazhen/Sazhen/firmware/misc
    - cp    /builds/Sazhen/Sazhen/misc/*  /builds/Sazhen/Sazhen/firmware/misc
    - ls
    - cat   /builds/Sazhen/Sazhen/misc/target_build_subproject_header.mk
    - cat   /builds/Sazhen/Sazhen/firmware/misc/target_build_subproject_header.mk
    - export PATH="$PATH:/work/gcc-arm-none-eabi-4_9-2015q3/bin"
    - arm-none-eabi-gcc --version
    - makepp BUILD_MODE=debug BUILD_PORT=target-device-rev1 clean
    - echo "$(makepp BUILD_MODE=debug BUILD_PORT=target-device-rev1 -j4)"
  artifacts:
    paths:
    - "/builds/Sazhen/Sazhen/firmware/BUILD_target-device-rev1_debug/SazhenN_HOST_target-device-rev1_firmware.elf"
    - "/builds/Sazhen/Sazhen/firmware/BUILD_target-device-rev1_debug/SazhenN_HOST_target-device-rev1_firmware.hex"
    name: "Sazhen_$CI_JOB_ID"
    when: on_success
    expire_in: 30 day
    
    job2:
  stage: dfubuild
  tags: 
    - dfu
  script:
    - cd ..\
    - git.exe clone --progress -v "http://Kozma:test12345@gitlab.d5.lan:8880/DevTools/dfu_bin.git"
    - cd dfu_bin
    - copy ..\Sazhen\firmware\BUILD_target-device-rev1_debug\SazhenN_HOST_target-device-rev1_firmware.hex .\
    - ./stm32_dfu_generator.exe SazhenN_HOST_target-device-rev1_firmware.hex SazhenN_HOST_target-device-rev1_firmware.dfu
    - copy SazhenN_HOST_target-device-rev1_firmware.dfu ..\Sazhen
    - cd ..\
    - remove-item dfu_bin -force -Recurse
    - cd .\Sazhen
  artifacts:
    paths:
      - "SazhenN_HOST_target-device-rev1_firmware.dfu"
    name: "Sazhen_dfu"
    when: on_success
    expire_in: 30 day
  dependencies:
    - job1


