build-sazhen:
  stage: build
  image: gitlab.d5.lan:5005/sazhen/sazhen:latest  
stages:
  - build
build: 
   stage: build
   script: 
  - sudo docker run -v $(pwd):/work/test -it gitlab.d5.lan:5005/sazhen/sazhen
  - cd /work/test/HOST/firmware
  - mkdir /work/test/HOST/firmware/misc
  - cp /work/test/HOST/misc /work/test/HOST/firmware/misc 
  - makepp clean
  - makepp -j8

