#ifndef ALE_SETTINGS_H
#define ALE_SETTINGS_H

//#define CALLER_IGNORE_RX
#define	NOT_TURN_OFF_RX_WHEN_MSG_RECEIVED
//#define	CALLER_DT_INCREMENT					(-300)
#define	TX_DATA_SUPERPHASE_INC_TIME			100
#define	RX_DATA_SUPERPHASE_INC_TIME			100

//#define	MIN_SIGN_FORM_TX					4
#define	START_SIGN_FORM						0		//	STT SIGN FORM FOR CALL FREQ WORKING

#endif // ALE_SETTINGS_H

