/*
 * qmguielement_template.h
 *
 *  Created on: 10 марта 2016 г.
 *      Author: Egor Dudyak
 */

#ifndef QMGUIELEMENT_TEMPLATE_H_
#define QMGUIELEMENT_TEMPLATE_H_

/*Управление цветовой схемой осуществляется через опцию компиляции GUI_COLOR_SCEME=GCS_BLACK/GCS_WHITE*/
#ifdef GCS_LIGHT
	#define GENERAL_TEXT_COLOR				G_BLACK
	#define GENERAL_FORE_COLOR				G_BLACK
	#define GENERAL_BACK_COLOR				G_WHITE
	#define MENU_ITEM_INACTIVE_BACK_COLOR	G_WHITE
	#define MENU_ITEM_INACTIVE_TEXT_COLOR	G_BLACK
	#define MENU_ITEM_ACTIVE_BACK_COLOR		G_BLUE_LIGHT
	#define MENU_ITEM_ACTIVE_TEXT_COLOR		G_BLACK
	#define SPBOX_ACTIVE_BACK_COLOR			G_GREY
	#define SPBOX_ACTIVE_TEXT_COLOR			G_BLACK
	#define SPBOX_INACTIVE_BACK_COLOR		G_WHITE
	#define SPBOX_INACTIVE_TEXT_COLOR		G_BLACK
	#define BATTERY_HIGH_COLOR				G_GREEN
	#define BATTERY_MID_COLOR				G_YELLOW
	#define BATTERY_LOW_COLOR				G_RED
#endif

#ifdef GCS_DARK
	#define GENERAL_TEXT_COLOR				G_YELLOW
	#define GENERAL_FORE_COLOR				G_YELLOW
	#define GENERAL_BACK_COLOR				G_BLACK
	#define MENU_ITEM_INACTIVE_BACK_COLOR	G_BLACK
	#define MENU_ITEM_INACTIVE_TEXT_COLOR	G_YELLOW
	#define MENU_ITEM_ACTIVE_BACK_COLOR		G_YELLOW
	#define MENU_ITEM_ACTIVE_TEXT_COLOR		G_BLACK
	#define SPBOX_ACTIVE_BACK_COLOR			G_YELLOW
	#define SPBOX_ACTIVE_TEXT_COLOR			G_BLACK
	#define SPBOX_INACTIVE_BACK_COLOR		G_BLACK
	#define SPBOX_INACTIVE_TEXT_COLOR		G_YELLOW
	#define BATTERY_HIGH_COLOR				G_YELLOW
	#define BATTERY_MID_COLOR				G_YELLOW
	#define BATTERY_LOW_COLOR				G_YELLOW
#endif


#endif /* QMGUIELEMENT_TEMPLATE_H_ */
